#!/bin/sh
# /etc/init.d/picam

### BEGIN INIT INFO
# Provides:          picamweb
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a servo
### END INIT INFO


case "$1" in 
    start)
        echo "Starting picam web"
        python /home/pi/picam/picam-git/PiCam/picam.py
       ;;
    stop)
        echo "Stopping picam web"
        pkill -f picam.py
        ;;
    *)
        echo "Usage: /etc/init.d/servod start|stop"
        exit 1
        ;;
esac

exit 0
